### ISSUE TITLE
concatenated annotation files from model evaluation 

### ISSUE THREAD

**Issue by canihaveabravo** [ChristianBergler/ANIMAL-SPOT#6]
Hello, 

Is there a way to concatenate raven annotation files output from evaluation on multiple .wav files in sequence?

This would be very useful for viewing continuous datasets of files in sequence in Raven with one raven selection table. 

Thanks for your help,
Lorenzo

**Comment by ChristianBergler** [comment]
Hi Lorenzo,

no unfortunately there is not. But this should be very easy and straightforward to combine individual raven files, coming from ANIMAL-SPOT, into one continuous file. Due to the fact that there are plenty of different user-specific purposes and wishes, we decided to report only those raven files, but left any type of post-evaluation/-processing open to the users. Everybody can use the results of ANIMAL-SPOT for their specific use-cases, but of course, has to write the piece of software.
